import type { IconType } from 'react-icons'
import { FaJava } from 'react-icons/fa6'
import {
  SiCelery,
  SiClaude,
  SiCplusplus,
  SiCss,
  SiDjango,
  SiDocker,
  SiExpress,
  SiFastapi,
  SiFirebase,
  SiFlask,
  SiGit,
  SiGithub,
  SiGithubcopilot,
  SiGitlab,
  SiGooglecloud,
  SiGraphql,
  SiHtml5,
  SiJavascript,
  SiJenkins,
  SiJest,
  SiJira,
  SiKubernetes,
  SiLinux,
  SiMongodb,
  SiMysql,
  SiNestjs,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiPostgresql,
  SiPython,
  SiRabbitmq,
  SiReact,
  SiRedis,
  SiSass,
  SiSpringboot,
  SiSqlite,
  SiTailwindcss,
  SiTerraform,
  SiTypescript,
  SiUbuntu,
  SiVercel,
  SiVuedotjs,
  SiWebpack,
} from 'react-icons/si'
import { VscAzure, VscTerminalCmd } from 'react-icons/vsc'
import { TbBrandCSharp, TbBrandOpenai, TbBrandVite, TbCloud } from 'react-icons/tb'

const ICON_MAP: Record<string, IconType> = {
  python: SiPython,
  python3: SiPython,
  java: FaJava,
  javascript: SiJavascript,
  typescript: SiTypescript,
  html: SiHtml5,
  html5: SiHtml5,
  css: SiCss,
  css3: SiCss,
  sass: SiSass,
  scss: SiSass,
  'c#': TbBrandCSharp,
  csharp: TbBrandCSharp,
  'c++': SiCplusplus,
  react: SiReact,
  reactjs: SiReact,
  'react.js': SiReact,
  vue: SiVuedotjs,
  vuejs: SiVuedotjs,
  'vue.js': SiVuedotjs,
  nextjs: SiNextdotjs,
  'next.js': SiNextdotjs,
  nodejs: SiNodedotjs,
  'node.js': SiNodedotjs,
  express: SiExpress,
  nestjs: SiNestjs,
  django: SiDjango,
  flask: SiFlask,
  fastapi: SiFastapi,
  'spring boot': SiSpringboot,
  springboot: SiSpringboot,
  tailwind: SiTailwindcss,
  tailwindcss: SiTailwindcss,
  vite: TbBrandVite,
  webpack: SiWebpack,
  graphql: SiGraphql,
  'rest api': SiFastapi,
  postgresql: SiPostgresql,
  postgres: SiPostgresql,
  postgresql3: SiPostgresql,
  mongodb: SiMongodb,
  mysql: SiMysql,
  sqlite: SiSqlite,
  redis: SiRedis,
  rabbitmq: SiRabbitmq,
  firebase: SiFirebase,
  docker: SiDocker,
  kubernetes: SiKubernetes,
  jenkins: SiJenkins,
  git: SiGit,
  github: SiGithub,
  gitlab: SiGitlab,
  jira: SiJira,
  jest: SiJest,
  celery: SiCelery,
  nginx: SiNginx,
  linux: SiLinux,
  ubuntu: SiUbuntu,
  terraform: SiTerraform,
  vercel: SiVercel,
  aws: TbCloud,
  'amazon s3': TbCloud,
  s3: TbCloud,
  azure: VscAzure,
  'azure pipelines': VscAzure,
  gcp: SiGooglecloud,
  'google cloud': SiGooglecloud,
  openai: TbBrandOpenai,
  chatgpt: TbBrandOpenai,
  claude: SiClaude,
  'claude code': SiClaude,
  'github copilot': SiGithubcopilot,
  cursor: VscTerminalCmd,
  codex: VscTerminalCmd,
}

const BRAND_COLORS: Record<string, string> = {
  java: '#ED8B00',
  celery: '#37814A',
  python: '#3776AB',
  python3: '#3776AB',
  javascript: '#F7DF1E',
  typescript: '#3178C6',
  html: '#E34F26',
  html5: '#E34F26',
  css: '#1572B6',
  css3: '#1572B6',
  react: '#61DAFB',
  reactjs: '#61DAFB',
  'react.js': '#61DAFB',
  vue: '#4FC08D',
  vuejs: '#4FC08D',
  'vue.js': '#4FC08D',
  django: '#092E20',
  fastapi: '#009688',
  'rest api': '#009688',
  tailwind: '#06B6D4',
  tailwindcss: '#06B6D4',
  graphql: '#E10098',
  postgresql: '#4169E1',
  postgres: '#4169E1',
  mongodb: '#47A248',
  redis: '#DC382D',
  rabbitmq: '#FF6600',
  firebase: '#FFCA28',
  docker: '#2496ED',
  git: '#F05032',
  jenkins: '#D24939',
  'spring boot': '#6DB33F',
  springboot: '#6DB33F',
  nodejs: '#5FA04E',
  'node.js': '#5FA04E',
}

export function getSkillIcon(name: string): { Icon: IconType | null; color: string } {
  const key = name.trim().toLowerCase()
  return {
    Icon: ICON_MAP[key] ?? null,
    color: BRAND_COLORS[key] ?? 'currentColor',
  }
}
